apiVersion: v1
kind: Service
metadata:
  name: travel-page-service
spec:
  selector:
    app: travel-page
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
